// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("creationDate");

                    b.Property<string>("username");

                    b.HasKey("userId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            userId = -1,
                            creationDate = new DateTime(2019, 10, 30, 1, 16, 31, 336, DateTimeKind.Local).AddTicks(4534),
                            username = "Name -1"
                        },
                        new
                        {
                            userId = -2,
                            creationDate = new DateTime(2019, 10, 30, 1, 16, 31, 341, DateTimeKind.Local).AddTicks(1000),
                            username = "Name -2"
                        },
                        new
                        {
                            userId = -3,
                            creationDate = new DateTime(2019, 10, 30, 1, 16, 31, 341, DateTimeKind.Local).AddTicks(1024),
                            username = "Name -3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
